apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-19-jan # The name of the Kubernetes Deployment
  labels:
    app: react-app
spec:
  replicas: 3 # The number of pods to be created
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
      - name: react-app # Name of the container
        image: deepaks374/react-app:latest # Docker image for the React.js app
        imagePullPolicy: Always # Ensure Kubernetes pulls the latest image from Docker Hub
        ports:
        - containerPort: 3000 # Port exposed by the container
